# Write a program to create two matrix and perform various operations. (matrix)
Matrix1 <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)
Matrix2 <- matrix(9:1, nrow = 3, ncol = 3, byrow = TRUE)
cat("Sum : \n")
print(Matrix1 + Matrix2)
cat("Subtraction : \n")
print(Matrix1 - Matrix2)
cat("Multiplication : \n")
print(Matrix1 * Matrix2)
cat("Divsion : \n")
print(Matrix1 %/% Matrix2)
cat("Modulus : \n")
print(Matrix1 %% Matrix2)
cat("Transpose of matrix 1 : \n")
print(t(Matrix1))
cat("Transpose of matrix 2 : \n")
print(t(Matrix2))